# syntax=docker/dockerfile:1
ARG QUALIFIED_ASR_BASE=dgx-qwen3-asr:vllm023-615e858c
FROM ${QUALIFIED_ASR_BASE}

RUN --mount=type=bind,source=.,target=/tmp/flashinfer-wheels \
    python3 -m pip install --no-cache-dir --no-deps --force-reinstall \
      /tmp/flashinfer-wheels/flashinfer_python-0.6.18-py3-none-any.whl \
      /tmp/flashinfer-wheels/flashinfer_jit_cache-0.6.18-cp39-abi3-manylinux_2_28_aarch64.whl \
      /tmp/flashinfer-wheels/flashinfer_cubin-0.6.18-py3-none-any.whl
